# Generated by Django 3.2.6 on 2021-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_manufacturer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginemodel',
            name='engine_code',
            field=models.CharField(default='power = 100hp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enginemodel',
            name='power',
            field=models.CharField(default='code = BAM', max_length=10),
            preserve_default=False,
        ),
    ]
